"""Chromium interaction tests with a memory Storage adapter.
The test environment blocks URL navigation by policy; the bundled HTML is loaded
with Playwright set_content. This does NOT claim a published/HTTP/file-origin test.
Install Playwright separately to run this optional developer-only suite.
"""
from pathlib import Path
import json, sys, tempfile, zipfile, hashlib, os, uuid
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
OUT=Path(os.environ.get('PIGGY_TEST_OUTPUT',str(ROOT.parent/'piggy-test-output')))
OUT.mkdir(parents=True,exist_ok=True)
html=(ROOT/'dist/index.html').read_text(encoding='utf-8')
results=[];errors=[]
def check(name,condition,detail=''):
    results.append({'name':name,'passed':bool(condition),'detail':detail})
    if not condition: raise AssertionError(name+': '+str(detail))
def ready(browser, viewport=None, seed=None):
    context=browser.new_context(viewport=viewport or {'width':1440,'height':960},accept_downloads=True,has_touch=True)
    page=context.new_page();page.set_default_timeout(5000)
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.evaluate('''seed=>{window.__testStore={...(seed||{})};Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>Object.hasOwn(window.__testStore,k)?window.__testStore[k]:null,setItem:(k,v)=>window.__testStore[k]=String(v),removeItem:k=>delete window.__testStore[k],clear:()=>window.__testStore={}}});}''',seed)
    page.set_content(html,wait_until='load');page.wait_for_selector('#loading',state='hidden');return context,page

def fresh(page,start=True):
    page.evaluate('''()=>{PIGGY.state=PIGGY.State.fresh();PIGGY.UI.home();PIGGY.State.save(PIGGY.state);}''')
    if start:page.locator('#depart').click()

with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium'),headless=True,args=['--no-sandbox'])
    try:
        ctx,page=ready(browser)
        check('Bundled HTML boots with all 12 SVG assets',page.evaluate('Object.keys(PIGGY.Art.images).length===12&&Object.values(PIGGY.Art.images).every(i=>i.complete&&i.naturalWidth>0)'))
        check('No horizontal overflow on desktop',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        page.screenshot(path=str(OUT/'home.png'))
        page.locator('#depart').click();x=page.evaluate('PIGGY.game.player.x');page.keyboard.down('d');page.wait_for_timeout(400);page.keyboard.up('d')
        check('Keyboard movement changes world position',page.evaluate('PIGGY.game.player.x')>x+35)
        fresh(page)
        page.keyboard.press('e');page.keyboard.down('d');page.wait_for_timeout(200);page.keyboard.up('d')
        check('Carried pig follows player',page.evaluate('PIGGY.game.pig.carrying&&Math.abs(PIGGY.game.pig.x-PIGGY.game.player.x)<3'))
        values=page.evaluate('''()=>{const g=PIGGY.game;g.player.punch=0;g.player.kick=0;g.punch();g.kick();const r=[g.player.punch,g.player.kick];g.mode='pause';return r;}''')
        check('Carry blocks punch but allows kick',values[0]==0 and values[1]>0)
        fresh(page)
        values=page.evaluate('''()=>{const P=PIGGY,g=P.game;P.state.party=[];g.helpers=[];g.enemies=[g.makeEnemy({id:'wind-main-0',x:g.player.x+80,type:'slime'})];const e=g.enemies[0];e.active=true;g.punch();for(let i=0;i<18;i++)g.tick(1/60);const hp=e.hp;g.kick();for(let i=0;i<3;i++)g.tick(1/60);const drops=g.progress.drops.length;g.player.x=e.x;g.tick(1/60);const coins=P.state.runCoins;g.mode='pause';return {hp,drops,coins,dead:g.progress.dead.includes('wind-main-0')};}''')
        check('Punch has two damage events',values['hp']==10,values)
        check('Enemy drops ground coins and walking collects them',values['drops']==3 and values['coins']==12 and values['dead'],values)
        page.evaluate("PIGGY.game.mode='play';PIGGY.game.finish('return');PIGGY.UI.home()")
        check('Manual return banks collected coins',page.evaluate('PIGGY.state.coins')==132)
        page.locator('#depart').click()
        check('Killed monster stays dead on re-entry',page.evaluate("!PIGGY.game.enemies.some(e=>e.id==='wind-main-0')"))
        fresh(page)
        values=page.evaluate('''()=>{const P=PIGGY,g=P.game;g.player.hp=0;P.state.runCoins=83;g.tick(1/60);return {safe:P.state.coins,run:P.state.runCoins,hp:P.state.player.hp,active:P.state.active};}''')
        check('Player death keeps money without healing',values=={'safe':203,'run':0,'hp':0,'active':False},values)
        page.locator('#result-home').click();page.locator('#depart').click()
        check('Dead player is directed to treatment rather than starting',page.locator('#modal-title').inner_text()=='가방 · 치료' and page.evaluate('!PIGGY.state.active'))
        page.locator('[data-item="potion"]').drag_to(page.locator('[data-heal-target="player"]'))
        check('Drag-and-drop consumes one potion and restores 50 HP',page.evaluate('PIGGY.state.player.hp===50&&PIGGY.state.inventory.potion===2'))
        fresh(page)
        values=page.evaluate('''()=>{const P=PIGGY,g=P.game;g.pig.hp=0;P.state.runCoins=95;g.tick(1/60);return {safe:P.state.coins,run:P.state.runCoins,hp:P.state.pig.hp,active:P.state.active};}''')
        check('Pig death loses only expedition balance',values=={'safe':120,'run':0,'hp':0,'active':False},values)
        page.locator('#result-home').click();page.locator('[data-view="bag"]').first.click()
        page.locator('[data-item="repair"]').click();page.locator('[data-heal-target="pig"]').click()
        check('Click alternative repairs pig without natural recovery',page.evaluate('PIGGY.state.pig.hp===80&&PIGGY.state.inventory.repair===1'))
        fresh(page)
        page.evaluate('''()=>{PIGGY.game.enemies=[];PIGGY.state.helpers.sprout={hp:0,revive:10};}''')
        page.locator('#pause').click();page.locator('#pause-source').click()
        before=page.evaluate('PIGGY.state.helpers.sprout.revive');page.wait_for_timeout(350)
        page.evaluate('PIGGY.game.tick(4)')
        check('Source viewer pauses revival and simulation',page.evaluate('PIGGY.state.helpers.sprout.revive')==before and page.evaluate("PIGGY.game.mode==='pause'"))
        page.locator('[data-close]').click()
        values=page.evaluate('''()=>{const P=PIGGY,g=P.game;g.enemies=[];P.state.helpers.sprout={hp:0,revive:10};for(let i=0;i<599;i++)g.tick(1/60);let before=P.state.helpers.sprout.hp;for(let i=0;i<3;i++)g.tick(1/60);g.mode='pause';return {before,after:P.state.helpers.sprout.hp,distance:Math.abs(g.helpers[0].x-g.pig.x)};}''')
        check('Companion revives after 10 simulation seconds at 50% by the pig',values['before']==0 and values['after']==40 and values['distance']<20,values)
        fresh(page)
        page.keyboard.press('q');check('Q toggles companion guarding',page.evaluate("PIGGY.state.mode==='guard'"))
        fresh(page)
        page.evaluate('''()=>{let g=PIGGY.game;g.player.x=1880;g.pig.x=1900;g.interact();}''')
        check('Chest grants coins and medicine with a contents dialog',page.evaluate("PIGGY.state.runCoins===70&&PIGGY.state.inventory.potion===4&&PIGGY.game.progress.opened.includes('w-c1')") and page.locator('#modal-title').inner_text()=='보물상자를 열었어요')
        page.locator('#loot-close').click()
        page.evaluate('''()=>{const g=PIGGY.game;g.interact();}''')
        check('Opened chest cannot grant its reward twice',page.evaluate('PIGGY.state.runCoins===70&&PIGGY.state.inventory.potion===4'))
        page.evaluate('''()=>{const g=PIGGY.game;g.player.x=2460;g.pig.x=2460;g.pig.carrying=true;g.interact();}''')
        check('Branch portal moves player, pig and helpers to a saved sub-area',page.evaluate("PIGGY.game.roomId==='hollow'&&PIGGY.game.progress.visited.includes('hollow')&&Math.abs(PIGGY.game.pig.x-PIGGY.game.player.x)<60"))
        page.evaluate('''()=>{const g=PIGGY.game;g.player.x=180;g.pig.x=180;g.loadRoom('cave');g.player.x=2590;g.pig.x=2590;g.interact();}''')
        check('Hidden helper registers immediately',page.evaluate('!!PIGGY.state.helpers.scout') and '잎새' in page.locator('#modal-title').inner_text())
        fresh(page)
        values=page.evaluate('''()=>{const P=PIGGY,g=P.game;g.progress.dead=P.allEnemies(g.map).map(e=>e.id).slice(0,-1);g.spawnBoss();const locked=!g.enemies.some(e=>e.type==='boss');g.progress.dead=P.allEnemies(g.map).map(e=>e.id);g.spawnBoss();const open=g.enemies.some(e=>e.type==='boss');const boss=g.enemies.find(e=>e.type==='boss');g.hitEnemy(boss,9999);g.tick(1/60);return {locked,open,cleared:g.progress.cleared,unlocked:P.state.unlocked.includes('amber')};}''')
        check('All regular monsters gate the boss and clear unlocks next map',all(values.values()),values)
        page.locator('#result-retry').click()
        check('Explicit replay resets completed map',page.evaluate('PIGGY.game.progress.dead.length===0&&!PIGGY.game.progress.cleared'))
        fresh(page,False)
        page.locator('[data-view="skills"]').first.click();page.locator('[data-buy-type="skill"][data-id="run"]').click()
        check('Skill shop actually charges coins and learns running',page.evaluate('PIGGY.state.skills.run===1&&PIGGY.state.coins===20'))
        page.locator('[data-close]').click();page.locator('#depart').click();page.keyboard.down('d');page.keyboard.down('Shift');page.wait_for_timeout(250)
        check('Purchased running increases speed without jumping',page.evaluate('PIGGY.game.player.vx>310&&PIGGY.game.player.y===PIGGY.CONFIG.ground'));page.keyboard.up('Shift');page.keyboard.up('d')
        fresh(page,False)
        page.evaluate('''()=>{const P=PIGGY,s=P.state;s.coins=10000;for(const t of P.SKILLS)P.State.purchase(s,'skill',t.id);P.UI.refreshHome();}''')
        page.locator('#depart').click()
        values=page.evaluate('''()=>{const P=PIGGY,g=P.game;g.enemies=[];const used={};for(const id of ['spin','dash','fire','fly','gun']){P.state.equipped=[id];g.pig.carrying=false;g.skill(0);used[id]=(g.player.skills[id]||0)>0;for(let i=0;i<40;i++)g.tick(1/60);}g.player.skills.fire=0;g.pig.carrying=true;P.state.equipped=['fire'];g.skill(0);used.carryBlocked=g.player.skills.fire===0;g.mode='pause';return used;}''')
        check('All five special actions activate, with hand-use carry restriction',all(values.values()),values)
        fresh(page)
        page.evaluate('''()=>{const P=PIGGY,g=P.game;g.progress.dead=['wind-main-0'];P.state.runCoins=37;g.player.hp=61;g.snapshot();}''')
        seed=page.evaluate('window.__testStore')
        ctx2,page2=ready(browser,seed=seed)
        check('Saved expedition restores health, coins and dead enemy record, paused',page2.evaluate("PIGGY.state.runCoins===37&&PIGGY.game.player.hp===61&&!PIGGY.game.enemies.some(e=>e.id==='wind-main-0')&&PIGGY.game.mode==='pause'"),'Memory Storage adapter; not real browser-origin persistence')
        ctx2.close()
        fresh(page,False);page.locator('#source-btn').click();page.locator('[data-source="src/game.js"]').click()
        check('Source viewer shows the exact executing original module',page.locator('#source-pre').inner_text()==(ROOT/'src/game.js').read_text())
        page.screenshot(path=str(OUT/'source.png'))
        private_marker=str(uuid.uuid4())
        page.evaluate("v=>PIGGY.state.privateTestMarker=v",private_marker)
        with page.expect_download() as d:page.locator('#source-zip').click()
        zip_path=OUT/'source-download.zip';d.value.save_as(str(zip_path))
        with zipfile.ZipFile(zip_path) as z:
            check('Public ZIP passes CRC and includes runnable sources and handoff',z.testzip() is None and all(n in z.namelist() for n in ['index.html','source-bundle.js','src/game.js','scripts/build.py','HANDOFF.md','AGENTS.md','assets/pig.svg']))
            check('ZIP excludes individual save data',all(private_marker.encode() not in z.read(n) for n in z.namelist()))
            check('Downloaded game source matches original byte-for-byte',z.read('src/game.js')==(ROOT/'src/game.js').read_bytes())
        with page.expect_download() as d:page.locator('#download-file').click()
        d.value.save_as(str(OUT/'game-source-download.js'))
        check('Per-file download matches visible source',(OUT/'game-source-download.js').read_bytes()==(ROOT/'src/game.js').read_bytes())
        fresh(page,False);page.locator('#save-tools').click()
        invalid=json.dumps({'schema':999}).encode()
        page.locator('#import-save').set_input_files({'name':'bad.json','mimeType':'application/json','buffer':invalid});page.wait_for_timeout(100)
        check('Unsupported save import leaves current state untouched',page.evaluate('PIGGY.state.coins===120'))
        new=page.evaluate('PIGGY.State.fresh()');new['coins']=777
        page.locator('#import-save').set_input_files({'name':'restore.json','mimeType':'application/json','buffer':json.dumps(new).encode()});page.wait_for_selector('#confirm-import')
        check('Valid save import requests confirmation before replacing data',page.evaluate('PIGGY.state.coins===120'))
        with page.expect_download() as d:page.locator('#confirm-import').click()
        d.value.save_as(str(OUT/'before-import-backup.json'))
        check('Confirmed import backs up old data and restores selected save',page.evaluate('PIGGY.state.coins===777') and json.loads((OUT/'before-import-backup.json').read_text())['coins']==120)
        fresh(page)
        page.evaluate('''()=>{const g=PIGGY.game;g.player.x=620;g.pig.x=560;g.helpers[0].x=520;g.camera=170;g.player.pose='kick';g.player.age=.2;g.enemies[0].x=720;g.enemies[0].active=true;g.roomTitle=0;g.mode='pause';}''')
        page.wait_for_timeout(120);page.screenshot(path=str(OUT/'gameplay.png'))
        ctxm,pm=ready(browser,{'width':920,'height':480})
        pm.locator('#depart').click();pm.wait_for_timeout(80)
        check('Mobile landscape fits viewport without horizontal scrolling',pm.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        for selector in ['[data-hold="a"]','[data-hold="d"]','#punch-btn','#kick-btn']:
            box=pm.locator(selector).bounding_box();check('Mobile control visible: '+selector,box and box['width']>=40 and box['height']>=40 and box['y']+box['height']<=480,box)
        # A genuine touch sequence exercises pointer capture, not synthetic PointerEvents.
        box=pm.locator('[data-hold="d"]').bounding_box();cdp=ctxm.new_cdp_session(pm)
        x0=pm.evaluate('PIGGY.game.player.x');pt={'x':box['x']+box['width']/2,'y':box['y']+box['height']/2,'id':1}
        cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[pt]});pm.wait_for_timeout(250);cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
        check('Real touch press moves player and release clears held input',pm.evaluate('PIGGY.game.player.x')>x0+15 and pm.evaluate('PIGGY.game.keys.size')==0)
        pm.screenshot(path=str(OUT/'mobile-landscape.png'))
        ctxp,pp=ready(browser,{'width':390,'height':844})
        check('Portrait home fits viewport without horizontal overflow',pp.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        check('Portrait home exposes all four navigation destinations',pp.locator('.mobile-nav button').count()==4 and pp.locator('.mobile-nav').is_visible())
        pp.locator('.mobile-nav [data-view="helpers"]').click()
        check('Portrait navigation opens companion collection',pp.locator('#modal-title').inner_text()=='조수 모음집')
        pp.locator('[data-close]').click()
        pp.locator('.mobile-nav [data-view="skills"]').click()
        check('Portrait navigation opens skill shop',pp.locator('#modal-title').inner_text()=='기술 배우기')
        pp.locator('[data-close]').click()
        pp.screenshot(path=str(OUT/'mobile-portrait.png'))
        check('No browser JavaScript exceptions during suite',not errors,errors)
        ctx.close();ctxm.close();ctxp.close()
    finally:
        browser.close()
        output={'version':json.loads((ROOT/'package.json').read_text())['version'],'method':'Chromium set_content + in-memory Storage adapter; use the parent HTTP suite for actual origin persistence','results':results,'passed':sum(r['passed'] for r in results),'failed':sum(not r['passed'] for r in results),'javascript_errors':errors}
        (OUT/'browser-results.json').write_text(json.dumps(output,ensure_ascii=False,indent=2))
        print(json.dumps({'passed':output['passed'],'failed':output['failed'],'errors':errors},ensure_ascii=False))
