"""Actual HTTP tests for account UI, combat lab and the v0.11 mechanics."""
from pathlib import Path
import json, os, secrets, uuid
from playwright.sync_api import sync_playwright
URL=os.environ.get('PIGGY_URL','http://127.0.0.1:4180/piggy-quest/index.html')
OUT=Path(os.environ.get('PIGGY_TEST_OUTPUT','/tmp/piggy-v11-browser'));OUT.mkdir(parents=True,exist_ok=True)
results=[]
def check(name,ok,detail=None):
    results.append({'name':name,'passed':bool(ok),'detail':detail});assert ok,(name,detail)
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
    context=browser.new_context(viewport={'width':1366,'height':900});page=context.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    response=page.goto(URL);page.wait_for_function('window.PIGGY?.game&&document.querySelector("#loading").hidden',timeout=30000)
    check('Game and account selection load over actual HTTP',response.status==200 and page.locator('#device-form').count()==1)
    page.fill('#device-name','첫 모험');page.locator('#device-form button').click()
    check('A new device account starts tutorial automatically',page.evaluate('PIGGY.game.mode==="play"&&!PIGGY.state.tutorial.complete&&PIGGY.state.tutorial.step===0'))
    check('All four native weapon assets decode',page.evaluate('["bow","arrow","quiver","fire-jet"].every(id=>PIGGY.Art.images[id].naturalWidth>0)'))
    page.evaluate('PIGGY.UI.pause();PIGGY.Accounts.show()');page.fill('#device-name','다른 모험');page.locator('#device-form button').click()
    page.evaluate('PIGGY.state.coins=777;PIGGY.State.save(PIGGY.state);PIGGY.UI.pause();PIGGY.Accounts.show()');page.locator('[data-profile]').filter(has_text='첫 모험').click()
    check('Device accounts keep their own independent money',page.evaluate('PIGGY.state.coins===120&&PIGGY.Accounts.current.name==="첫 모험"'))
    page.evaluate('PIGGY.game.mode="play";PIGGY.game.keys.add("d");for(let n=0;n<35;n++)PIGGY.game.tick(1/60);PIGGY.game.clearInput()')
    check('Tutorial movement advances after real simulation movement',page.evaluate('PIGGY.state.tutorial.step===1'))
    page.evaluate('PIGGY.game.jump()');check('Tutorial accepts actual jump',page.evaluate('PIGGY.state.tutorial.step===2'))
    page.evaluate('PIGGY.game.punch()');check('Tutorial accepts actual attack',page.evaluate('PIGGY.state.tutorial.step===3'))
    page.evaluate('const g=PIGGY.game;g.player.y=600;g.player.vy=0;g.player.grounded=true;g.pig.x=g.player.x+20;g.interact()');check('Tutorial uses E to carry the pig',page.evaluate('PIGGY.state.tutorial.step===4&&PIGGY.game.pig.carrying'))
    page.evaluate('PIGGY.UI.worldMap()');check('Tutorial map step uses red location marker',page.evaluate('PIGGY.state.tutorial.step===5') and page.locator('[data-current-position="true"]').get_attribute('fill')=='#d74646');page.evaluate('PIGGY.UI.close()')
    page.evaluate('const g=PIGGY.game;const e=g.enemies.find(e=>e.hp>0);g.hitEnemy(e,9999)');check('First real monster kill completes tutorial',page.evaluate('PIGGY.state.tutorial.complete'))
    page.evaluate('const g=PIGGY.game;g.mode="play";g.enemies=[];g.player.x=5600;g.pig.x=5650;g.pig.carrying=false;g.player.hp=0;PIGGY.state.runCoins=101;g.beginRevive();g.tick(1/60);g.mode="pause";g.draw()')
    page.screenshot(path=str(OUT/'revival-countdown.png'))
    check('Player death keeps location and run coins during countdown',page.evaluate('PIGGY.game.player.x===5600&&PIGGY.game.player.revive>9&&PIGGY.state.runCoins===101'))
    before=page.evaluate('PIGGY.game.player.revive');page.evaluate('PIGGY.game.tick(3)');check('Pause freezes player revival',page.evaluate('PIGGY.game.player.revive')==before)
    page.evaluate('const g=PIGGY.game;g.mode="play";for(let n=0;n<601;n++)g.tick(1/60);g.mode="pause"')
    check('Player revives at the pig with half HP and preserved kills',page.evaluate('PIGGY.game.player.hp===50&&PIGGY.game.player.x===5650&&PIGGY.game.progress.dead.length>0&&PIGGY.state.runCoins===101'))
    page.evaluate('PIGGY.game.finish("return")');check('Voluntary return banks rounded-down half',page.evaluate('PIGGY.state.coins===170&&PIGGY.state.runCoins===0'));page.evaluate('PIGGY.UI.home()')
    saved=page.evaluate('JSON.stringify({...PIGGY.state,updatedAt:""})');storage=page.evaluate('localStorage.getItem(PIGGY.Accounts.key())');page.click('#developer-btn')
    check('Lab starts with no player, no companions and no monsters',page.evaluate('PIGGY.Lab.active&&PIGGY.Lab.battle.player.hp===0&&!PIGGY.Lab.battle.helpers.length&&!PIGGY.Lab.battle.enemies.length'))
    page.click('#lab-pause');canvas=page.locator('#lab-canvas');bounds=canvas.bounding_box()
    def drag_card(selector,fraction):
        bounds=canvas.bounding_box();card=page.locator(selector);card.scroll_into_view_if_needed();a=card.bounding_box();page.mouse.move(a['x']+a['width']/2,a['y']+a['height']/2);page.mouse.down();page.mouse.move(bounds['x']+bounds['width']*fraction,bounds['y']+bounds['height']*.75,steps=12);page.mouse.up()
    drag_card('[data-spawn="helper:archer"]',.28);drag_card('[data-spawn="enemy:cave-guard"]',.6)
    check('Pointer drag places actual companion and monster actors',page.evaluate('PIGGY.Lab.battle.helpers[0].id==="archer"&&PIGGY.Lab.battle.enemies[0].type==="cave-guard"'))
    page.evaluate('PIGGY.Lab.scoped(()=>{for(let n=0;n<180;n++)PIGGY.Lab.battle.tick(1/60);PIGGY.Lab.battle.draw()})')
    check('Lab archer runs real AI and ballistic damage',page.evaluate('PIGGY.Lab.battle.enemies[0].hp<PIGGY.Lab.battle.enemies[0].max'))
    page.screenshot(path=str(OUT/'archer-lab.png'))
    bounds=canvas.bounding_box();page.mouse.move(bounds['x']+bounds['width']*.85,bounds['y']+bounds['height']*.25);page.mouse.down();page.mouse.move(bounds['x']+bounds['width']*.55,bounds['y']+bounds['height']*.25,steps=10);page.mouse.up();check('Scene drag pans camera',page.evaluate('PIGGY.Lab.battle.camera>200'))
    page.select_option('#lab-map','wind:cave');check('Choosing cave loads actual cave biome',page.evaluate('PIGGY.Lab.battle.room.biome==="cave"'))
    page.select_option('#lab-map','wind:main');page.evaluate('PIGGY.Lab.scoped(()=>{const b=PIGGY.Lab.battle;b.spawn("helper:flame",350);b.spawn("enemy:rock",675);for(let n=0;n<45;n++)b.tick(1/60);b.draw()})');page.screenshot(path=str(OUT/'fire-jet-lab.png'))
    check('Lab flame uses a growing continuous jet',page.evaluate('PIGGY.Lab.battle.allyEffects.some(f=>f.type==="pillar"&&f.r>200)'))
    page.select_option('#lab-map','wind:main');page.evaluate('PIGGY.Lab.scoped(()=>{const b=PIGGY.Lab.battle;b.spawn("helper:sword",350);b.spawn("enemy:cave-guard",460);for(let n=0;n<47;n++)b.tick(1/60);b.draw()})');page.screenshot(path=str(OUT/'sword-windup-lab.png'))
    check('Sword has distinct backward windup before side slash',page.evaluate('PIGGY.Lab.battle.helpers[0].pose==="sword"&&PIGGY.Companions.swordFrame(PIGGY.Lab.battle.helpers[0].age).gripDir[0]<0'))
    page.select_option('#lab-map','wind:cave');page.evaluate('PIGGY.Lab.scoped(()=>{const b=PIGGY.Lab.battle;b.spawn("dummy:player",450);b.spawn("enemy:cave-archer",730);for(let n=0;n<130;n++)b.tick(1/60)})')
    check('Ordinary stick fighter can receive actual monster attacks',page.evaluate('PIGGY.Lab.battle.player.hp<100'))
    check('Lab cannot alter device save bytes',page.evaluate('localStorage.getItem(PIGGY.Accounts.key())')==storage)
    page.click('#lab-close');check('Leaving lab restores unchanged bank/progress/state',page.evaluate('JSON.stringify({...PIGGY.state,updatedAt:""})')==saved)
    if os.environ.get('PIGGY_SKIP_ONLINE')!='1':
        # Secure API UI on the isolated server; generated test password never logged.
        name='vm'+uuid.uuid4().hex[:10];password=secrets.token_hex(20)
        page.click('#account-btn');page.locator('summary').click();page.fill('#online-name',name);page.fill('#online-password',password);page.click('[data-online="register"]');page.wait_for_function('PIGGY.Accounts.current?.type==="online"',timeout=15000)
        check('Online registration creates a separate account and starts tutorial',page.evaluate('PIGGY.game.mode==="play"&&!PIGGY.state.tutorial.complete'))
        page.evaluate('PIGGY.game.mode="pause";PIGGY.state.coins=426;PIGGY.state.tutorial.complete=true;PIGGY.State.save(PIGGY.state);PIGGY.Accounts.flush()')
        page.wait_for_function('async()=>{const r=await fetch("/api/piggy/save",{credentials:"include"});const d=await r.json();return d.save?.coins===426}',timeout=15000)
        check('Online account autosave persists on the actual SQLite API',True)
        other=browser.new_context(viewport={'width':1280,'height':850});second=other.new_page();second.goto(URL);second.wait_for_function('window.PIGGY?.game&&document.querySelector("#loading").hidden',timeout=30000);second.locator('summary').click();second.fill('#online-name',name);second.fill('#online-password',password);second.click('[data-online="login"]');second.wait_for_function('PIGGY.Accounts.current?.type==="online"',timeout=15000)
        check('A separate browser logs in and resumes server save',second.evaluate('PIGGY.state.coins===426&&PIGGY.state.tutorial.complete'))
    check('No uncaught browser errors',not errors,errors)
    # Mobile layout and touch drag against fresh anonymous account prompt.
    mobile=browser.new_context(viewport={'width':844,'height':390},is_mobile=True,has_touch=True);m=mobile.new_page();m.goto(URL);m.wait_for_function('window.PIGGY?.game&&document.querySelector("#loading").hidden',timeout=30000);m.fill('#device-name','터치 계정');m.locator('#device-form button').click();m.evaluate('PIGGY.Lab.open();PIGGY.Lab.pause()');m.screenshot(path=str(OUT/'mobile-lab.png'));check('Mobile lab shows usable scene and palette',m.locator('#lab-canvas').bounding_box()['height']>100 and m.locator('.lab-palette').is_visible())
    card=m.locator('[data-spawn="helper:brawler"]').bounding_box();target=m.locator('#lab-canvas').bounding_box();cdp=mobile.new_cdp_session(m)
    start={'x':card['x']+card['width']/2,'y':card['y']+card['height']/2,'id':1};end={'x':target['x']+target['width']*.35,'y':target['y']+target['height']*.7,'id':1}
    cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[start]})
    for n in range(1,9):cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':start['x']+(end['x']-start['x'])*n/8,'y':start['y']+(end['y']-start['y'])*n/8,'id':1}]})
    cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
    check('Real touch drag places a lab companion',m.evaluate('PIGGY.Lab.battle.helpers.some(h=>h.id==="brawler")'))
    browser.close()
(OUT/'results.json').write_text(json.dumps(results,ensure_ascii=False,indent=2));print(json.dumps({'passed':len(results),'output':str(OUT)},ensure_ascii=False))
