"""v0.7 actual HTTP/Chromium: A scenery scroll, shovel discovery, cave combat and multitouch.
Only isolated browser saves are modified. Explicit combat scenes are not a full manual clear.
"""
import json,os
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
URL=os.environ.get('PIGGY_URL','http://127.0.0.1:4173/piggy-quest/index.html')
OUT=Path(os.environ.get('PIGGY_TEST_OUTPUT','/tmp/piggy-v070-exploration'));OUT.mkdir(parents=True,exist_ok=True)
checks=[];errors=[]
def check(name,v):
 assert v,name
 checks.append(name)
 print('PASS',name,flush=True)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium',headless=True)
 ctx=b.new_context(viewport={'width':1180,'height':820},has_touch=True)
 p=ctx.new_page();p.on('pageerror',lambda e:errors.append(str(e)))
 check('Actual HTTP responds',p.goto(URL).status==200);p.wait_for_selector('#loading',state='hidden')
 check('Native A atlases load and default sound has no toggle button',p.evaluate("PIGGY.VERSION==='0.7.0'&&PIGGY.Art.images['a-scenery'].naturalWidth===1774&&PIGGY.Art.images['a-props'].naturalWidth===1536&&PIGGY.Art.images['cave-monsters'].naturalWidth===2172&&Object.keys(PIGGY.Pixel.tiles).length===16&&PIGGY.state.settings.sound&&!document.getElementById('sound-play')&&!document.getElementById('sound')"))
 check('Camp shows three genuinely affordable equipment purchases',p.evaluate("document.querySelectorAll('.camp-shortcuts button').length===3&&document.getElementById('camp-skills-offer').textContent==='구매 가능 3개'"))
 p.locator('.camp-shortcuts [data-view="skills"]').click()
 check('Shovel is affordable and expensive skills stay disabled',p.locator('[data-id="shovel"]').is_enabled() and p.locator('[data-id="spin"]').is_disabled() and p.locator('[data-id="shovel"] .purchase-note').inner_text()=='구매 가능')
 p.locator('[data-close]').click();p.locator('#depart').click();p.wait_for_timeout(120)
 p.evaluate('PIGGY.game.enemies=[]')
 cdp=ctx.new_cdp_session(p)
 def point(selector,ident,dx=0):
  box=p.locator(selector).bounding_box();assert box,selector
  return {'x':box['x']+box['width']/2+dx,'y':box['y']+box['height']/2,'id':ident}
 joy=point('#joystick',1,30)
 cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[joy]});p.wait_for_timeout(100)
 action=point('#interact-btn',2)
 cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[joy,action]})
 check('Moving touch plus E acts immediately without releasing movement',p.evaluate("PIGGY.game.pig.carrying&&PIGGY.game.keys.has('d')"))
 cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[action]})
 check('Releasing E preserves the joystick movement pointer',p.evaluate("PIGGY.game.keys.has('d')"))
 jump=point('#jump-btn',3);cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[joy,jump]});p.wait_for_timeout(120)
 check('Jump works simultaneously with held joystick and carried pig',p.evaluate("PIGGY.game.player.y<570&&PIGGY.game.keys.has('d')&&PIGGY.game.pig.y===PIGGY.game.player.y-PIGGY.CONFIG.carryHeight"))
 cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]});p.wait_for_timeout(800)
 check('Free jump lands on the ground and movable world objects are absent',p.evaluate('PIGGY.game.player.y===600&&PIGGY.game.player.grounded&&PIGGY.game.objects.length===0&&PIGGY.MAPS.every(m=>Object.values(m.rooms).every(r=>r.objects.length===0))'))
 p.evaluate("()=>{const g=PIGGY.game;g.clearInput();g.player.x=3000;g.player.vx=0;g.camera=2600;g.pig.carrying=true;g.pig.x=3000;g.roomTitle=0;}")
 p.wait_for_timeout(150)
 p.evaluate("""()=>{const P=PIGGY,c=document.createElement('canvas');c.width=1280;c.height=720;P.Pixel.background(c.getContext('2d'),P.game.camera,0,'forest','evacuated-forest');window.__beforeBG=Array.from(c.getContext('2d').getImageData(0,0,1280,500).data);window.__beforeCamera=P.game.camera;window.__beforePlans=P.Pixel.backgroundPlan(P.game.camera,'forest','evacuated-forest');}""")
 p.keyboard.down('d');p.wait_for_timeout(1000);p.keyboard.up('d')
 v=p.evaluate("""()=>{const P=PIGGY,c=document.createElement('canvas');c.width=1280;c.height=720;P.Pixel.background(c.getContext('2d'),P.game.camera,0,'forest','evacuated-forest');const d=c.getContext('2d').getImageData(0,0,1280,500).data;let changed=0;for(let i=0;i<d.length;i+=64)if(Math.abs(d[i]-window.__beforeBG[i])+Math.abs(d[i+1]-window.__beforeBG[i+1])+Math.abs(d[i+2]-window.__beforeBG[i+2])>12)changed++;const plans=P.Pixel.backgroundPlan(P.game.camera,'forest','evacuated-forest'),shared=plans.filter(a=>window.__beforePlans.some(b=>a.id===b.id));return {camera:P.game.camera-window.__beforeCamera,changed,continuous:shared.every(a=>Math.abs(a.x-window.__beforePlans.find(b=>b.id===a.id).x+(P.game.camera-window.__beforeCamera)*.36)<1e-6)};}""")
 check('Actual walking moves the painted background as well as the world',v['camera']>140 and v['changed']>5000)
 check('Overlapping panorama sections retain stable identities while scrolling',v['continuous'])
 p.screenshot(path=str(OUT/'a-forest-scrolling.png'))
 # Set up the sealed site, then use actual E input, actual shop purchase and real origin reload.
 v=p.evaluate("""()=>{const P=PIGGY,g=P.game,q=g.room.portals.find(p=>p.secret);g.clearInput();g.player.x=q.x;g.player.y=600;g.player.vx=g.player.vy=0;g.player.grounded=true;g.pig.carrying=false;g.pig.x=q.x-60;g.camera=q.x-500;g.cameraY=P.World.height(g.room,q.x)*.75;return {id:q.target,name:g.map.rooms[q.target].name,hidden:!P.World.chart(g).includes(g.map.rooms[q.target].name),locked:!P.Exploration.accessible(g,q),ends:(P.World.chart(g).match(/data-end=/g)||[]).length};}""")
 check('Sealed passage and connector stay off the map before actual discovery',v['hidden'] and v['locked'])
 check('Visible connections expose matching entry and exit markers',v['ends']>=8 and v['ends']%2==0)
 p.keyboard.press('e')
 check('Without a shovel E inspects soil without entering or changing excavation',p.evaluate("!PIGGY.game.travel&&PIGGY.game.roomId==='main'&&PIGGY.game.interactionLabel()==='흙의 흔적 조사'&&Object.keys(PIGGY.game.progress.excavations).length===0"))
 p.locator('#pause').click();p.locator('#return-home').click();p.locator('#result-home').click()
 p.locator('.camp-shortcuts [data-view="skills"]').click();p.locator('[data-id="shovel"]').click()
 check('Real shop button charges 90 coins and equips no special skill slot',p.evaluate('PIGGY.state.coins===30&&PIGGY.state.skills.shovel===1&&PIGGY.state.equipped.length===0'))
 p.locator('[data-close]').click();p.locator('#depart').click();p.evaluate('PIGGY.game.enemies=[]')
 p.keyboard.press('e');p.keyboard.press('e')
 check('E dig animation starts and rapid repeated E cannot skip the recovery',p.evaluate("PIGGY.game.player.pose==='dig'&&PIGGY.game.player.dig>0&&Object.values(PIGGY.game.progress.excavations)[0]===1"))
 p.screenshot(path=str(OUT/'shovel-digging.png'));p.locator('#pause').click()
 before=p.evaluate('PIGGY.game.player.dig');p.wait_for_timeout(160)
 check('Pause freezes digging, its sound schedule and simulation time',p.evaluate(f'PIGGY.game.player.dig==={before}'))
 p.reload();p.wait_for_selector('#loading',state='hidden')
 check('One dig and purchased shovel survive actual origin reload',p.evaluate("PIGGY.game.mode==='pause'&&PIGGY.state.coins===30&&PIGGY.state.skills.shovel===1&&Object.values(PIGGY.game.progress.excavations)[0]===1&&PIGGY.game.objects.length===0"))
 p.locator('#continue').click();p.keyboard.press('e');p.wait_for_timeout(540);p.keyboard.press('e');p.wait_for_timeout(540)
 check('Three separate digs open the entrance but do not yet reveal it on the map',p.evaluate("()=>{const P=PIGGY,g=P.game,q=g.room.portals.find(p=>p.secret);return g.progress.excavations[q.digId]===3&&P.Exploration.accessible(g,q)&&!g.progress.visited.includes(q.target)&&!P.World.chart(g).includes(g.map.rooms[q.target].name);}"))
 p.screenshot(path=str(OUT/'underground-entrance.png'))
 p.keyboard.press('e');p.wait_for_timeout(80)
 check('Entering starts the companion walking transition',p.evaluate("!!PIGGY.game.travel&&PIGGY.game.roomId==='main'"))
 p.locator('#pause').click();age=p.evaluate('PIGGY.game.travel.age');p.wait_for_timeout(180)
 check('Pause freezes the walking transition clock',p.evaluate(f'PIGGY.game.travel.age==={age}'))
 p.screenshot(path=str(OUT/'walking-transition-paused.png'))
 p.locator('#continue').click();p.wait_for_function('!PIGGY.game.travel',timeout=2500)
 check('Actual entry discovers the underground room and adds it to the map',p.evaluate("PIGGY.game.roomId==='cave'&&PIGGY.game.progress.visited.includes('cave')&&PIGGY.World.chart(PIGGY.game).includes('비밀 동굴')"))
 check('Underground has three stronger new enemy types and a cave background',p.evaluate("PIGGY.game.room.biome==='cave'&&PIGGY.Pixel.scene('forest','cave')==='cave'&&new Set(PIGGY.game.enemies.map(e=>e.type)).size===3&&PIGGY.game.enemies.every(e=>e.max>=105)"))
 p.screenshot(path=str(OUT/'cave-entry.png'))
 # Explicit combat setup in the live game exercises actual fixed-step AI and projectile collision.
 v=p.evaluate("""()=>{const P=PIGGY,g=P.game;g.helpers=[];P.state.party=[];g.enemies=[g.makeEnemy({id:'test-archer',type:'cave-archer',x:1300})];const e=g.enemies[0];e.active=true;e.cd=0;g.player.x=1000;g.pig.x=700;g.player.y=600;g.player.inv=99;g.tick(1/60);const warned=e.windup>0&&!g.enemyShots.length;g.mode='pause';const windup=e.windup;g.tick(1);const frozen=e.windup===windup;g.mode='play';for(let i=0;i<42;i++)g.tick(1/60);const a=g.enemyShots[0],vy=a?.vy,y=a?.y;g.tick(1/60);const curved=a&&a.gravity===720&&a.vy>vy&&a.y<y;g.mode='pause';return {warned,frozen,curved};}""")
 check('Cave archer telegraphs, pauses and fires an actual rising ballistic arrow',all(v.values()))
 p.screenshot(path=str(OUT/'cave-archer.png'))
 v=p.evaluate("""()=>{const P=PIGGY,g=P.game;g.mode='play';g.enemies=[];g.enemyShots=[];g.player.x=1000;g.player.y=600;g.player.vx=0;g.player.dir=1;g.player.pose='idle';g.player.inv=0;g.player.hp=100;P.state.skills.woodshield=1;g.player.shieldRaised=true;g.pig.x=700;g.enemyShots=[{type:'arrow',x:1100,y:510,vx:-450,vy:0,gravity:720,r:3,life:2,damage:17}];for(let i=0;i<12;i++)g.tick(1/60);g.mode='pause';return g.enemyShots.length===0&&g.shieldHits>0&&g.player.hp===100;}""")
 check('Raised wooden shield deletes a cave arrow with no player damage',v)
 p.screenshot(path=str(OUT/'cave-shield.png'))
 v=p.evaluate("""()=>{const P=PIGGY,g=P.game;delete P.state.skills.woodshield;g.player.shieldRaised=false;g.player.hp=100;g.player.inv=0;g.player.y=600;g.player.vy=0;g.player.grounded=true;g.player.x=1100;g.pig.x=700;g.mode='play';g.enemies=[g.makeEnemy({id:'test-charger',type:'cave-charger',x:900})];const e=g.enemies[0];e.active=true;e.cd=0;g.tick(1/60);const warn=e.windup>0;for(let i=0;i<36;i++)g.tick(1/60);g.jump();for(let i=0;i<25;i++)g.tick(1/60);const avoided=g.player.hp===100&&e.x>1040&&g.player.y<500;g.mode='pause';return {warn,avoided};}""")
 check('Telegraphed cave charge advances while the player jumps over it',all(v.values()))
 # Found companion and optional boss condition, preserving the existing expedition rules.
 p.evaluate("()=>{const g=PIGGY.game;g.mode='play';g.enemies=[];g.player.x=g.room.helper.x;g.pig.x=g.player.x;g.player.y=600;g.player.vy=0;g.interact();}")
 check('Hidden companion immediately joins expedition without a paid slot',p.evaluate("PIGGY.game.helpers.some(h=>h.id==='scout')&&PIGGY.state.helpers.scout&&PIGGY.state.slots===1&&PIGGY.game.progress.guests.includes('scout')"))
 p.locator('#found-close').click()
 check('Hidden cave monsters may remain alive when the surface boss becomes available',p.evaluate("()=>{const P=PIGGY,g=P.game;g.progress.dead=P.requiredEnemies(g.map).map(e=>e.id);g.loadRoom('main');return g.remaining()===0&&g.enemies.some(e=>e.type==='boss')&&g.map.rooms.cave.enemies.some(e=>!g.progress.dead.includes(e.id));}"))
 p.evaluate('PIGGY.game.enemies=[]');p.locator('#pause').click();p.locator('#pause-controls').click()
 before=p.locator('#kick-btn').bounding_box()['width']
 p.locator('#control-target').select_option('punch-btn');p.locator('#control-size').fill('76');p.locator('#control-size').dispatch_event('input')
 check('Selected punch size changes independently of kick and joystick',abs(p.locator('#punch-btn').bounding_box()['width']-76)<1 and p.locator('#kick-btn').bounding_box()['width']==before and p.locator('#joystick').bounding_box()['width']==112)
 p.locator('#control-target').select_option('joystick');p.locator('#control-size').fill('138');p.locator('#control-size').dispatch_event('input');p.locator('#control-save').click()
 check('Individual punch and joystick sizes persist without changing global defaults',p.evaluate("PIGGY.state.settings.controls.sizes['punch-btn']===76&&PIGGY.state.settings.controls.sizes.joystick===138&&PIGGY.state.settings.controls.size===56"))
 p.reload();p.wait_for_selector('#loading',state='hidden')
 check('Guest, discovered cave and individual layout survive actual reload',p.evaluate("PIGGY.game.helpers.some(h=>h.id==='scout')&&PIGGY.game.progress.visited.includes('cave')&&PIGGY.state.settings.controls.sizes.joystick===138&&Math.abs(document.getElementById('punch-btn').getBoundingClientRect().width-76)<1"))
 check('No browser JavaScript exceptions',not errors)
 b.close()
result={'version':'0.7.0','url':URL,'passed':len(checks),'failed':0,'checks':checks,'method':'Actual HTTP Chromium, real CDP multitouch and keyboard, real purchase and storage reload. Cave AI/shield/boss edge cases use explicit isolated scene setup; not native iPad/Safari or a full manual clear.'}
(OUT/'exploration-results.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');print(json.dumps(result,ensure_ascii=False))
