/** Device profiles are explicitly local; online accounts require a configured API. */
(function(P){
 'use strict';
 const registryKey='piggy-quest-accounts-v1',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let profiles=[],current=null,revision=0,timer=0,pending=null,syncing=false,blocked=false;
 function store(){localStorage.setItem(registryKey,JSON.stringify({profiles,current:current?.id}));}
 function init(){try{const r=JSON.parse(localStorage.getItem(registryKey)||'{}');profiles=(r.profiles||[]).filter(p=>p&&typeof p.id==='string'&&typeof p.name==='string'&&['device','online'].includes(p.type)).slice(0,40);current=profiles.find(p=>p.id===r.current&&p.type==='device')||null;
   if(!profiles.length&&localStorage.getItem(P.CONFIG.saveKey)){current={id:'legacy',name:'기존 원정',type:'device'};profiles.push(current);store();}}catch{profiles=[];current=null;}}
 const identifier=()=>crypto.randomUUID?.()||Array.from(crypto.getRandomValues(new Uint8Array(16)),v=>v.toString(16).padStart(2,'0')).join('');
 const key=()=>!current||current.id==='legacy'?P.CONFIG.saveKey:'piggy-quest-account:'+current.id;
 function address(value){const u=new URL(value||location.origin);if(u.origin===location.origin&&/^https?:$/.test(u.protocol))return u.origin;if(u.protocol!=='https:'||u.username||u.password||u.pathname!=='/'||u.search||u.hash)throw new Error('온라인 서버의 HTTPS 주소만 입력하세요.');return u.origin;}
 async function request(origin,path,options={}){const response=await fetch(origin+'/api/piggy/'+path,{credentials:'include',...options,headers:{'Content-Type':'application/json',...options.headers}});let data;try{data=await response.json();}catch{throw new Error('이 주소에는 계정 서버가 연결되지 않았어요. 이 기기 계정으로 먼저 이용할 수 있습니다.');}if(!response.ok||!data.ok)throw new Error(data.error||'계정 서버에 연결하지 못했어요.');return data;}
 function queue(s){if(!current||current.type!=='online'||blocked)return;pending=JSON.parse(JSON.stringify(s));if(!timer&&!syncing)timer=setTimeout(flush,1800);}
 async function flush(){clearTimeout(timer);timer=0;if(!pending||syncing||!current||current.type!=='online'||blocked)return;const account=current,save=pending;pending=null;syncing=true;
   try{const result=await request(account.origin,'save',{method:'PUT',body:JSON.stringify({save,revision})});if(current===account){revision=result.revision;document.getElementById('account-btn').title='온라인 저장 완료';}}
   catch(e){blocked=true;P.UI.toast('이 기기 기록은 보존했습니다. '+e.message);}finally{syncing=false;if(pending&&!blocked)timer=setTimeout(flush,1800);}}
 function activate(profile,state,isNew=false){current=profile;blocked=false;revision=0;pending=null;clearTimeout(timer);timer=0;store();P.state=state||P.State.load().state;P.game.clearInput();P.UI.home();label();if(isNew||!P.state.tutorial.complete&&!P.state.active)P.UI.depart('wind');else if(P.state.active)P.UI.restoreActive();}
 function label(){const b=document.getElementById('account-btn');if(b)b.textContent=current?(current.type==='online'?'☁ ':'◯ ')+current.name:'로그인 · 계정';const f=document.querySelector('.hero-foot');if(f)f.textContent=current?.type==='online'?'온라인 계정 · 기기에도 자동 백업':'이 기기에 자동 저장 · 온라인 서버 연결 가능';}
 function show(){if(P.Lab?.active)return;P.UI.open('계정으로 모험 이어가기','이 기기 계정은 현재 브라우저에 저장됩니다. 다른 기기에서 이어 하려면 온라인 계정 서버를 연결하세요.',`<div class="dialog-content account-panel"><div class="account-list">${profiles.filter(p=>p.type==='device').map(p=>`<button class="secondary" data-profile="${esc(p.id)}">◯ ${esc(p.name)} <small>이 기기</small></button>`).join('')}</div><form id="device-form"><h3>이 기기 계정 추가</h3><label>계정 이름<input id="device-name" maxlength="24" minlength="2" required autocomplete="nickname"></label><button class="primary">추가하고 튜토리얼 시작</button></form><details><summary>온라인 로그인 · 계정 등록</summary><p class="smallnote">온라인 서버가 연결된 경우에만 다른 기기와 동기화됩니다. 현재 Pages 사이트에는 계정 서버가 배포되지 않았습니다.</p><form id="online-form"><label>계정 서버 주소<input id="account-origin" type="url" placeholder="https://계정서버주소" value="${esc(location.origin)}" required></label><label>계정 이름<input id="online-name" minlength="2" maxlength="24" autocomplete="username" required></label><label>비밀번호<input id="online-password" type="password" minlength="8" maxlength="128" autocomplete="current-password" required></label><div class="button-row"><button class="primary" type="submit" data-online="login">로그인</button><button class="secondary" type="submit" data-online="register">새 계정 등록</button></div></form></details><p id="account-error" class="warn" role="alert"></p>${current?.type==='online'?'<button id="account-logout" class="secondary">온라인 로그아웃</button>':''}</div>`,{kind:'account'});
   document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=async()=>{if(syncing)return;await flush();if(blocked&&current?.type==='online'){error('온라인 저장 문제를 해결하거나 저장 관리에서 먼저 백업하세요.');return;}activate(profiles.find(p=>p.id===b.dataset.profile));});
   const error=text=>document.getElementById('account-error').textContent=text;
   document.getElementById('device-form').onsubmit=async e=>{e.preventDefault();if(syncing)return;await flush();if(profiles.length>=40){error('계정은 최대 40개입니다.');return;}const name=document.getElementById('device-name').value.trim();if(name.length<2){error('이름을 두 글자 이상 입력하세요.');return;}if(profiles.some(p=>p.type==='device'&&p.name===name)){error('같은 이름의 계정이 있어요. 위에서 선택하세요.');return;}const profile={id:identifier(),name,type:'device'};profiles.push(profile);activate(profile,P.State.fresh(),true);P.State.save(P.state);};
   document.getElementById('online-form').onsubmit=async e=>{e.preventDefault();if(syncing)return;await flush();const buttons=[...document.querySelectorAll('[data-online]')];buttons.forEach(b=>b.disabled=true);
    try{const origin=address(document.getElementById('account-origin').value),name=document.getElementById('online-name').value,password=document.getElementById('online-password').value,action=e.submitter?.dataset.online||'login';
     const auth=await request(origin,action,{method:'POST',body:JSON.stringify({name,password})});document.getElementById('online-password').value='';const remote=await request(origin,'save');
     let profile=profiles.find(p=>p.type==='online'&&p.name===auth.user.name&&p.origin===origin);if(!profile){profile={id:identifier(),name:auth.user.name,type:'online',origin};profiles.push(profile);}const cacheKey='piggy-quest-account:'+profile.id,cached=localStorage.getItem(cacheKey);if(cached&&remote.save&&cached!==JSON.stringify(remote.save)&&!localStorage.getItem(cacheKey+'-recovery'))localStorage.setItem(cacheKey+'-recovery',cached);activate(profile,remote.save?P.State.normalize(remote.save):P.State.fresh(),!remote.save);revision=remote.revision;P.State.save(P.state);
    }catch(e){error(e.message);}finally{buttons.forEach(b=>b.disabled=false);}};
   const logout=document.getElementById('account-logout');if(logout)logout.onclick=async()=>{await flush();try{await request(current.origin,'logout',{method:'POST'});current=null;pending=null;clearTimeout(timer);timer=0;store();P.state=P.State.fresh();P.UI.home();label();show();}catch(e){error(e.message);}};
 }
 P.Accounts={recovery:()=>localStorage.getItem(key()+'-recovery'),init,key,queue,flush,show,label,get current(){return current;},get profiles(){return profiles;}};
})(globalThis.PIGGY=globalThis.PIGGY||{});
